name: Build Firmware

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.board }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        board: [DGNWG05LM, ZHWG11LM]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        submodules: true

    - name: Install Toolchain
      run: make install-toolchain

    - name: Build
      run: make BOARD=${{ matrix.board }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v7
      with:
        path: build/LumiRouter-${{ matrix.board }}.bin
        if-no-files-found: error
        archive: false
