name: Build Firmware

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: true

    - name: Install Python dependencies for SDK
      run: pip3 install --no-cache-dir xmltodict pycryptodome

    - name: Install Toolchain
      run: make install-toolchain

    - name: Build
      run: make

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v7
      with:
        path: build/*.bin
        archive: false
